---
- hosts: cb_pool
  remote_user: root
  any_errors_fatal: true
  serial: 1
  vars:
    couchbase_server_primary_node: "{{ groups['cb_pool'][0] }}"
  connection: local
  tasks:
    - shell: echo {{ couchbase_server_primary_node }} > ../../temp_couchbase_server_primary_node

- hosts: cb_pool
  remote_user: root
  any_errors_fatal: true
  sudo: true
  vars:
    couchbase_server_package_base_url:
    couchbase_server_package_name:
    couchbase_server_package_url: "{{ couchbase_server_package_base_url }}/{{ couchbase_server_package_name }}"

    couchbase_server_admin: Administrator
    couchbase_server_password: password
    couchbase_server_ram: "{{ ansible_memtotal_mb|int }}"
    couchbase_server_admin_port: 8091
    couchbase_server_home_path: /opt/couchbase

    couchbase_server_node: "{{ couchbase_server_primary_node }}"
    couchbase_server_bucket_name: default
    couchbase_server_bucket_name2: bucket-1
    couchbase_server_bucket_name3: bucket-2
    couchbase_server_bucket_type: couchbase
    couchbase_server_bucket_ram: 128
    couchbase_server_bucket_port: 11211
    couchbase_server_bucket_replica: 1

  tasks:
    - debug: msg="Downloading Couchbase server v. {{ couchbase_server_package_url }}"
    - name: set couchbase_server_primary_node variable
      set_fact:
        couchbase_server_primary_node: "{{ lookup('file', '../../temp_couchbase_server_primary_node') }}"

    - name: install-couchbase-server
      include: install-couchbase-server.yml

    - name: configure-couchbase-server
      include: configure-couchbase-server.yml
