---
- name: Stop Couchbase Service
  service: name=couchbase-server state=stopped
  ignore_errors: yes
- name: Uninstall couchbase server
  shell: rpm -e couchbase-server
  ignore_errors: yes
- name: Remove all couchbase server residue
  shell: rm -rf /opt/couchbase
- name: Download couchbase server
  get_url: url={{ couchbase_server_package_url }} dest=/tmp/{{ couchbase_server_package_name }}
- name: Install Couchbase Server
  yum: name=/tmp/{{ couchbase_server_package_name }} state=present
- name: Restart Couchbase Service
  service: name=couchbase-server state=restarted
- name: raise max file descriptors
  copy: src=files/security-nofiles-limit.conf dest=/etc/security/limits.d/20-nofiles.conf owner=root group=root mode=0644
#- name: Disable Transparent Huge Pages
#  shell: echo 'for i in /sys/kernel/mm/*transparent_hugepage/enabled; do echo never > $i; done' >> /etc/rc.local
#  shell: echo 'for i in /sys/kernel/mm/*transparent_hugepage/defrag; do echo never > $i; done' >> /etc/rc.local
#  shell: for i in /sys/kernel/mm/*transparent_hugepage/enabled; do echo never > $i; done